version: '3.8'

services:
  db_pg_15:
    image: postgres:15
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: nikita
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5400:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=*"]  

  backend:
    build: ./backend/DockerExampleDB
    ports:
      - "8080:8080"
    depends_on:
      - db_pg_15

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

volumes:
  postgres-data:
